
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: my_database_development

test:
  <<: *default
  database: my_database_development

production:
  <<: *default
  database: my_database_development
